eureka:
  client:
    service-url:
      defaultZone: ${eureka.url}
spring:
  session:
    store-type: redis
    redis:
      namespace: sessions
      flush-mode: immediate
  redis:
    host: 127.0.0.1
    port: 6379
feign:
  hystrix:
    enable: true