server:
  port: 8761
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceURL:
      defaultZone: ${eureka.url}
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000
    defaultZone: ${eureka.url}